#!/bin/bash
ONE_HUNDRED_MEG=107374182
max_log_directory_size=$ONE_HUNDRED_MEG
. /etc/clearwater/config

python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/clearwater-config-manager --prefix config_manager --maxsize $max_log_directory_size
