#!/bin/bash

set -ue

. /etc/clearwater/config

if [ $# -ne 2 ]
then
  echo "Usage: force_etcd_state [etcd_key] [json_file]"
  exit 1
fi

key=$1
json_file=$2

/usr/share/clearwater/cluster_manager/env/bin/python /usr/share/clearwater/cluster_manager/scripts/force_etcd_state.py $local_ip $json_file
