#!/bin/bash
ONE_HUNDRED_MEG=107374182
max_log_directory_size=$ONE_GIG
. /etc/clearwater/config

python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/cluster_manager --prefix cluster_manager --maxsize $max_log_directory_size
