#!/bin/bash

set -ue

local_site_name=site1
. /etc/clearwater/config

if [ $# -ne 0 ]
then
  echo "Usage: check_cluster_health"
  exit 1
fi

/usr/share/clearwater/clearwater-cluster-manager/env/bin/python /usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_health.py "$local_ip" "$local_site_name" "$remote_site_name"
