#!/bin/bash

set -ue

local_site_name="site1"
remote_site_name=""
. /etc/clearwater/config

if [ $# -ne 1 ]
then
  echo "Usage: load_from_memcached_cluster [node_type]"
  exit 1
fi

node_type=$1

/usr/share/clearwater/clearwater-cluster-manager/env/bin/python /usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_memcached_cluster.py $local_ip $local_site_name $remote_site_name $node_type
