#!/bin/bash

set -ue

. /etc/clearwater/config

if [ $# -ne 2 ]
then
  echo "Usage: mark_node_failed [etcd_key] [failed_node_ip]"
  exit 1
fi

key=$1
dead_node_ip=$2

/usr/share/clearwater/clearwater-cluster-manager/env/bin/python /usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed.py $local_ip $key $dead_node_ip
