#!/bin/bash

# Copyright (C) Metaswitch Networks 2015
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

set -ue

. /etc/clearwater/config

if [ -z $remote_site_name ]
then
  echo "remote_site_name setting must be set"
  exit 1
fi

if [ $# -ne 3 ]
then
  echo "Usage: mark_remote_node_failed [node_type] [datastore] [failed_node_ip]"
  exit 1
fi

node_type=$1
datastore=$2
dead_node_ip=$3

/usr/share/clearwater/clearwater-cluster-manager/env/bin/python /usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed.py ${management_local_ip:-$local_ip} $remote_site_name $node_type $datastore $dead_node_ip
