config_mgr_wheelhouse/* usr/share/clearwater/clearwater-config-manager/wheelhouse/
clearwater-config-manager.root/* /

# Install the etcd plugins
src/clearwater_etcd_plugins/clearwater_config_manager/shared_config_plugin.py /usr/share/clearwater/clearwater-config-manager/plugins/
src/clearwater_etcd_plugins/clearwater_config_manager/dns_json_plugin.py /usr/share/clearwater/clearwater-config-manager/plugins/
