#!/bin/bash
ONE_HUNDRED_MEG=$((100 * 1024 * 1024))
max_log_directory_size=$ONE_HUNDRED_MEG
. /etc/clearwater/config

python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/clearwater-etcd --prefix clearwater-etcd --maxsize $max_log_directory_size
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/clearwater-etcd --prefix mark_node_failed --maxsize $max_log_directory_size
