#!/bin/bash

# Project Clearwater - IMS in the Cloud
# Copyright (C) 2016 Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.
if [ -z $1 ]
then
  echo "You must provide a location to backup the configuration to"
  echo
  echo "Usage: $0 backup_directory"
  exit 1
fi

local_site_name=site1
etcd_key=clearwater
. /etc/clearwater/config

backup_directory=$1

top_key=/${etcd_key}/${local_site_name}/configuration/

clearwater-etcdctl ls ${top_key} > /tmp/backup_config.$$.stdout 2> /tmp/backup_config.$$.stderr

if [ $rc != 0 ] ; then
  echo "Failed to list keys from etcd config with return code $rc" >&2
  cat /tmp/backup_config.$$.stderr              >&2
  exit 2
fi


while read -r full_key; do
  key=${full_key/$top_key/}
  if [ "$key" != "apply_config" ]; then
    backup_file=${backup_directory}/$key

    clearwater-etcdctl get $full_key > "${backup_file}" 2> /tmp/backup_config.$key.$$

    rc=$?

    # Check the return code and log if appropriate.
    if [ $rc != 0 ] ; then
      echo "Failed to get $full_key from etcd config with return code $rc" >&2
      cat /tmp/backup_config.$key.$$              >&2
      exit 3
    fi
  fi
done < /tmp/backup_config.$$.stdout

rm /tmp/backup_config.$$.stderr
rm /tmp/backup_config.$$.stdout
