#!/bin/bash

# Copyright (C) Metaswitch Networks 2016
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

# Wrapper script for cw-config.py. Used to extract relevant variables
# from the config file.
. /etc/clearwater/config

/usr/share/clearwater/clearwater-config-manager/scripts/cw_config.py "$@" ${management_local_ip:-$local_ip} ${local_site_name:-"site1"} ${etcd_key:-"clearwater"}
