#!/bin/bash
# Copyright (C) Metaswitch Networks 2016
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

if [ -d /usr/share/clearwater/node_type.d ]; then
  . /usr/share/clearwater/node_type.d/$(ls /usr/share/clearwater/node_type.d | head -n 1)
fi
. /etc/clearwater/config

if [ -v etcd_cluster_key ]; then
  if [ "$use_single_restart_queue" == "Y" ]; then
    echo "apply_config"
  else
    echo "apply_config_$etcd_cluster_key"
  fi
else
  echo "apply_config"
fi
